# Generated by Django 5.2.15 on 2026-06-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aa_fleet_tool", "0002_fleetlayout"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activefleet",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="doctrine",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="doctrineship",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="doctrineship",
            name="role_hint",
            field=models.CharField(
                choices=[
                    ("any", "Any"),
                    ("dps", "DPS"),
                    ("logi", "Logi"),
                    ("booster", "Booster"),
                    ("fc", "FC"),
                    ("ewar", "EWAR"),
                    ("hauler", "Hauler"),
                    ("scout", "Scout"),
                ],
                default="any",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="fleetcommander",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="fleetlayout",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="fleetlayoutsquad",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="fleetlayoutwing",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="fleetmember",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="fleetmember",
            name="role",
            field=models.CharField(
                choices=[
                    ("fleet_commander", "FC"),
                    ("wing_commander", "WC"),
                    ("squad_commander", "SC"),
                    ("squad_member", "Member"),
                ],
                default="squad_member",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="fleetsquad",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="fleetwing",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
