# Generated by Django 5.2.15 on 2026-06-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aa_fleet_tool", "0007_fleetmember_station_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="fleetcommander",
            name="activated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fleetcommander",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
