# Generated by Django 5.2.15 on 2026-06-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aa_fleet_tool", "0008_fleetcommander_activated_at_fleetcommander_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="motdtemplate",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
    ]
