# Generated by Django 5.2.15 on 2026-06-13 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aa_fleet_tool", "0013_migrate_webhooks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fleettype",
            name="role_mention",
        ),
        migrations.RemoveField(
            model_name="fleettype",
            name="webhook_url",
        ),
    ]
