# Generated by Django 5.2.15 on 2026-06-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aa_fleet_tool", "0014_remove_fleettype_role_mention_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fleetsnapshot",
            name="in_system_booster",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="fleetsnapshot",
            name="in_system_dps",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="fleetsnapshot",
            name="in_system_ewar",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="fleetsnapshot",
            name="in_system_logi",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="fleetsnapshot",
            name="in_system_other",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="fleetsnapshot",
            name="in_system_total",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
